# Generated by Django 5.1.7 on 2025-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revaloriza_plus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('final', 'Usuario Final')], default='final', max_length=10),
        ),
    ]
